hydra:
  run:
    dir: /media/dmitry/data/kek/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: stylegan2/config_f

model:
  G:
    class: models.stylegan2.net.Generator
    params:
      img_res: 1024
      img_channels: 3
      num_classes: 0
      truncation_psi: 0.5
      truncation_cutoff: null
      randomize_noise: true
      impl: cuda_full
    weights: /media/dmitry/data/weights/ffhq_cuda_full/Gs.pth

sample:
  # Available modes: random | style-mixing
  mode: random
  # Num images to sample. Used only in `random` mode
  num_images: 22
  batch_size: 22
  device: cuda

style_mixing:
  # A list of seeds to sample row images deterministically. If specified, the number of row images
  # will be equal to the number of seeds (will ignore out.rows). null - use random seeds.
  row_seeds: null
  # Same as above, but for column images
  col_seeds: null
  # List of layers to use for mixing
  style_layers: 0 - 6

out:
  dir: /media/dmitry/data/kek/${now:%Y-%m-%d}/${now:%H-%M-%S}
  # prefix to be added to each file name
  prefix: ffhq_
  # expected model output range. Will be used to de-normalize images into pixel range [0 ... 255]
  range: [-1, 1]
  # max number of columns in image grid
  cols: 1
  # max number of rows in image grid. Use cols=1, rows=1 to save each image in a single file.
  rows: 1
