hydra:
  run:
    dir: /media/dmitry/data/kek/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: stylegan2/config_f

model:
  G:
    class: models.stylegan2.net.Generator
    params:
      img_res: 1024
      img_channels: 3
      num_classes: 0
      truncation_psi: 0.5
      truncation_cutoff: null
      randomize_noise: true
      impl: cuda_full
    weights: /media/dmitry/data/weights/ffhq_cuda_full/Gs.pth

sample:
  mode: random
  num_images: 22
  batch_size: 22
  device: cuda

out:
  dir: /media/dmitry/data/kek/${now:%Y-%m-%d}/${now:%H-%M-%S}
  # prefix to be added to each file name
  prefix: ffhq_
  # expected model output range. Will be used to de-normalize images into pixel range [0 ... 255]
  dynamic_range: [-1, 1]
  cols: 8
  rows: 2
