hydra:
  run:
    dir: /media/dmitry/data/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job_logging:
    handlers:
      file:
        filename: ${hydra.job.name}.log

defaults:
  - dataset: simple

general:
  gpu: 0
  seed: 333

distributed:
  backend: nccl
  url: env://

data:
  root: /media/dmitry/data/ffhq-dataset/thumbnails128x128
  extensions:
    - png
  loader:
    # batch size per each device
    batch_size: 32
    workers: 2

model:
  G:
    class: models.stylegan2.net.Generator
    params:
      img_res: 128
      img_channels: 3
      num_classes: 0
      latent_dim: 128
      style_dim: 512
      fmap_base: 2048
      fmap_decay: 1.0
      fmap_min: 1
      fmap_max: 512
      num_mapping_layers: 4
      mapping_hidden_dim: 128
      mapping_lr_mult: 0.01
      normalize_latent: true
      p_style_mix: 0.9
      w_avg_beta: 0.995
      truncation_psi: 0.5
      truncation_cutoff: null
      randomize_noise: true
      impl: ref
      blur_kernel: [1, 3, 3, 1]
  D:
    class: models.stylegan2.net.Discriminator
    params:
      img_res: 128
      img_channels: 3
      num_classes: 0
      fmap_base: 2048
      fmap_decay: 1.0
      fmap_min: 1
      fmap_max: 512
      mbstd_group_size: 4
      mbstd_num_features: 1
      impl: ref
      blur_kernel: [1, 3, 3, 1]

loss:
  G:
    class: models.stylegan2.loss.G_LogisticNSLoss_PathLenReg
    params:
      pl_decay: 0.01
      pl_reg_weight: 2.0
      pl_reg_interval: 4
      pl_minibatch_shrink: 2
  D:
    class: models.stylegan2.loss.D_LogisticLoss_R1
    params:
      r1_interval: 16
      r1_gamma: 100

optim:
  G:
    class: torch.optim.Adam
    params:
      lr: 0.002
      betas: [0.0, 0.99]
      eps: 1e-8
  D:
    class: torch.optim.Adam
    params:
      lr: 0.002
      betas: [0.0, 0.99]
      eps: 1e-8

train:
  epochs: 100
  epoch_length: -1
  # the effective batch size for gradient accumulation
  batch_size: 32

G_smoothing:
  enabled: true
  use_cpu: false
  num_kimg: 10.0
  upd_interval: 1

checkpoints:
  load: null
  save_dir: null
  interval_epoch: 1
  interval_iteration: 500
  max_checkpoints: 100

logging:
  model: false
  iter_freq: 100
  stats:
    - G_fake
    - G_loss
    - G_pl
    - D_real
    - D_fake
    - D_loss
    - D_r1

snapshots:
  enabled: true
  save_dir: null
  num_images: 32
  interval_iteration: 100
  dynamic_range: [-1, 1]
