model:
  G:
    class: models.stylegan2.net.Generator
    params:
      latent_dim: 128
      style_dim: 512
      fmap_base: 2048
      fmap_decay: 1.0
      fmap_min: 1
      fmap_max: 512
      num_mapping_layers: 4
      mapping_hidden_dim: 128
      mapping_lr_mult: 0.01
      normalize_latent: true
      blur_kernel: [1, 3, 3, 1]
  D:
    class: models.stylegan2.net.Discriminator
    params:
      fmap_base: 2048
      fmap_decay: 1.0
      fmap_min: 1
      fmap_max: 512
      mbstd_group_size: 4
      mbstd_num_features: 1
      blur_kernel: [1, 3, 3, 1]
